config/routes.rb
Rewsly::Application.routes.draw do
  devise_for :users
  root 'stories#index'
  resources :stories do
    resources :comments, only: :create
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :story
  has_many :upvotes
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, :link, :category, :upvotes, presence: true
  scope :popular, -> { where('upvotes >= ?', 4)}
  scope :recent, -> { where('created_at >= ?', Date.today)}

  belongs_to :user
  has_many :comments
  has_many :commenters, through: :comments, source: :user
  has_many :upvotes

  def self.search_for(query)
    where('title LIKE :query OR category LIKE :query', query: "%#{query}%")
  end

  def upvote
  end

end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :story
  belongs_to :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if user_signed_in?
      safe_comment = params.require(:comment).permit(:post).merge(story_id: params[:story_id])
      @comment = current_user.comments.create safe_comment
      redirect_to @comment.story
    else
      redirect_to new_user_session_path, alert: "Only logged in users can create comments"
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @stories = params[:q] ? Story.search_for(params[:q]) : Story.all
  end

  def show
    @story = Story.find params[:id]
    @comment = Comment.new(:story => @story)
  end

  def new
    @story = Story.new
  end

  def create
    safe_story_params = params.require(:story).permit(:title, :link, :category)
    @story = current_user.stories.build safe_story_params.merge(:upvotes => 1)

    if @story.save
      redirect_to @story
    else
      render :new
    end
  end

  def upvote
    @story = Story.find params[:id]
    @story.upvotes +=1
    @story.save
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rewsly</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/stories/_story.html.erb
<article>
  <li>
  <header>
    <%= link_to story.title, story.link %>
  </header>
  <p>Upvotes: <%= story.upvotes %> <%= button_to "Upvote", story.upvote, root_path %> | 
  Category: <%= story.category %> |
  <%= link_to "Comments", story %></p>
  </li>
</article>

app/views/stories/index.html.erb
<h1>Welcome to Rewsly</h1>

<h3><%= link_to "+ Add New Story", new_story_path %></h3>

<%= form_tag '/', method: :get do %>
  <%= search_field_tag :q, params[:q] %>
  <%= submit_tag "Search" %>
<% end %>

<br/>

<div id="stories">
  <ul>
    <%= render @stories %>
  </ul>
</div>

app/views/stories/new.html.erb
<% if @story.errors.any? %>
  <h2>The following errors prevented your story from saving:</h2>
  <ul>
  <% @story.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<h1>Add a new story</h1>
<%= form_for @story do |f| %>
  <fieldset>
    <legend>Story</legend>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :link %>
      <%= f.text_field :link %>
    </div>
    <div>
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>
  </fieldset>
  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<p><%= link_to @story.link, @story.link %>
<p><%= link_to "Back to home page", root_path %></p>

<%= form_for [@story, @comment] do |f| %>
  <p>
    <%= f.text_area :post, placeholder: "Add a comment...", :rows => 8, :cols => 40 %>
  </p>
  <%= f.submit %>
<% end %>

<ul class="comments">
  <% @story.comments.each do |comment| %>
    <li><%= "#{comment.user.try(:email)} posted: #{comment.post}" %></li>
  <% end %>
</ul>